### ISSUE TITLE
The rack status does not get updated some times when running cleanup

### ISSUE THREAD

**Issue by jsanda** [Orange-OpenSource/cassandra-k8s-operator#98] opened 2019-08-26 13:59 UTC
I discovered and discussed this issue in #90. 

Here are the steps to reproduce the problem as implemented in my test:

* Create a two node cluster spread across two racks. I think that the number of racks is irrelevant though. 
* Wait for cluster to be ready
* Set the labels to execute a cleanup on both Cassandra nodes.

Here is the code from the test function for setting the labels:

```go
	selector := metav1.LabelSelector{
		MatchExpressions: []metav1.LabelSelectorRequirement{
			{
				Key:      "statefulset.kubernetes.io/pod-name",
				Operator: metav1.LabelSelectorOpIn,
				Values:   []string{"cassandra-e2e-dc1-rack1-0", "cassandra-e2e-dc1-rack2-0"},
			},
		},
	}
	opts := metav1.ListOptions{
		LabelSelector: metav1.FormatLabelSelector(&selector),
	}

	pods := &v1.PodList{
		TypeMeta: metav1.TypeMeta{
			Kind:       "Pod",
			APIVersion: "v1",
		},
	}

	pods, err := f.KubeClient.CoreV1().Pods(namespace).List(opts)
	if err != nil {
		t.Fatalf("Failed to list pods: %s", err)
	}
	assert.Equal(t, 2, len(pods.Items))

	for _, pod := range pods.Items {
		pod.Labels["operation-name"] = "cleanup"
		pod.Labels["operation-status"] = "ToDo"
		if err := f.Client.Update(goctx.TODO(), &pod); err != nil {
			t.Fatalf("pod update failed: %s", err)
		}
	}
```

According to the status, the cleanup never runs on the second C* node:

```
  status:
    cassandraRackStatus:
      dc1-rack1:
        cassandraLastAction:
          Name: Initializing
          endTime: "2019-08-24T20:28:05Z"
          status: Done
        phase: Running
        podLastOperation:
          Name: cleanup
          endTime: "2019-08-24T20:30:01Z"
          operatorName: cassandra-k8s-operator-7cf67f66bb-w576w
          podsOK:
          - cassandra-e2e-dc1-rack1-0
          startTime: "2019-08-24T20:29:57Z"
          status: Done
      dc1-rack2:
        cassandraLastAction:
          Name: Initializing
          endTime: "2019-08-24T20:29:37Z"
          status: Done
        phase: Running
        podLastOperation: {}
    lastClusterAction: Initializing
    lastClusterActionStatus: Done
    phase: Running
    seedlist:
    - cassandra-e2e-dc1-rack1-0.cassandra-e2e.cassandra-e2e
    - cassandra-e2e-dc1-rack2-0.cassandra-e2e.cassandra-e2e
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
``` 

The cassandra logs however show that the operation did run:

```
INFO  [main] 2019-08-24 20:29:02,899 Server.java:156 - Starting listening for CQL clients on /0.0.0.0:9042 (unencrypted)...
INFO  [main] 2019-08-24 20:29:03,094 CassandraDaemon.java:556 - Not starting RPC server as requested. Use JMX (StorageService->startRPCServer()) or nodetool (enablethrift) to start it
INFO  [jolokia-1] 2019-08-24 20:29:58,411 CompactionManager.java:299 - No sstables to CLEANUP for system_distributed.view_build_status
INFO  [jolokia-1] 2019-08-24 20:29:58,593 CompactionManager.java:299 - No sstables to CLEANUP for system_distributed.parent_repair_history
INFO  [jolokia-1] 2019-08-24 20:29:58,633 CompactionManager.java:299 - No sstables to CLEANUP for system_distributed.repair_history
INFO  [jolokia-2] 2019-08-24 20:29:58,697 CompactionManager.java:299 - No sstables to CLEANUP for system_auth.resource_role_permissons_index
INFO  [jolokia-2] 2019-08-24 20:29:58,701 CompactionManager.java:299 - No sstables to CLEANUP for system_auth.role_members
INFO  [jolokia-2] 2019-08-24 20:29:58,707 CompactionManager.java:299 - No sstables to CLEANUP for system_auth.role_permissions
INFO  [jolokia-2] 2019-08-24 20:29:58,710 CompactionManager.java:299 - No sstables to CLEANUP for system_auth.roles
INFO  [jolokia-3] 2019-08-24 20:29:58,793 CompactionManager.java:299 - No sstables to CLEANUP for system_traces.sessions
INFO  [jolokia-3] 2019-08-24 20:29:58,795 CompactionManager.java:299 - No sstables to CLEANUP for system_traces.events
```
Here are the operator logs:

```
time="2019-08-24T20:29:37Z" level=info msg="[cassandra-e2e][dc1-rack2]: StatefulSet(Initializing): Replicas Number OK: ready[1]"
time="2019-08-24T20:29:37Z" level=info msg="Action Initializing is done!" cluster=cassandra-e2e
time="2019-08-24T20:29:57Z" level=info msg="Start operation" cluster=cassandra-e2e operation=Cleanup pod=cassandra-e2e-dc1-rack1-0 rack=dc1-rack1
time="2019-08-24T20:29:57Z" level=info msg="Operation start" cluster=cassandra-e2e hostName=cassandra-e2e-dc1-rack1-0.cassandra-e2e operation=Cleanup pod=cassandra-e2e-dc1-rack1-0 rack=dc1-rack1
time="2019-08-24T20:29:57Z" level=info msg="Execute the Jolokia Operation" cluster=cassandra-e2e operation=Cleanup pod=cassandra-e2e-dc1-rack1-0 rack=dc1-rack1
time="2019-08-24T20:29:57Z" level=info msg="Start operation" cluster=cassandra-e2e operation=Cleanup pod=cassandra-e2e-dc1-rack2-0 rack=dc1-rack2
time="2019-08-24T20:29:57Z" level=info msg="Operation start" cluster=cassandra-e2e hostName=cassandra-e2e-dc1-rack2-0.cassandra-e2e operation=Cleanup pod=cassandra-e2e-dc1-rack2-0 rack=dc1-rack2
time="2019-08-24T20:29:57Z" level=info msg="Execute the Jolokia Operation" cluster=cassandra-e2e operation=Cleanup pod=cassandra-e2e-dc1-rack2-0 rack=dc1-rack2
time="2019-08-24T20:29:58Z" level=info msg="[cassandra-e2e-dc1-rack2-0.cassandra-e2e]: Cleanup of keyspace system_distributed"
time="2019-08-24T20:29:58Z" level=info msg="[cassandra-e2e-dc1-rack2-0.cassandra-e2e]: Cleanup of keyspace system_auth"
time="2019-08-24T20:29:58Z" level=info msg="[cassandra-e2e-dc1-rack2-0.cassandra-e2e]: Cleanup of keyspace system_traces"
time="2019-08-24T20:29:58Z" level=error msg="Issue when updating CassandraCluster" cluster=cassandra-e2e err="Operation cannot be fulfilled on cassandraclusters.db.orange.com \"cassandra-e2e\": the object has been modified; please apply your changes to the latest version and try again"
time="2019-08-24T20:29:58Z" level=info msg="[cassandra-e2e-dc1-rack1-0.cassandra-e2e]: Cleanup of keyspace system_distributed"
time="2019-08-24T20:30:00Z" level=info msg="[cassandra-e2e-dc1-rack1-0.cassandra-e2e]: Cleanup of keyspace system_auth"
time="2019-08-24T20:30:00Z" level=info msg="[cassandra-e2e-dc1-rack1-0.cassandra-e2e]: Cleanup of keyspace system_traces"
time="2019-08-24T20:30:00Z" level=error msg="Issue when updating CassandraCluster" cluster=cassandra-e2e err="Operation cannot be fulfilled on cassandraclusters.db.orange.com \"cassandra-e2e\": the object has been modified; please apply your changes to the latest version and try again"
time="2019-08-24T20:30:00Z" level=error msg="Issue when updating CassandraCluster" cluster=cassandra-e2e err="Operation cannot be fulfilled on cassandraclusters.db.orange.com \"cassandra-e2e\": the object has been modified; please apply your changes to the latest version and try again"
```

The expected labels were set on the pod:

```
  labels:
    app: cassandracluster
    cassandracluster: cassandra-e2e
    cassandraclusters.db.orange.com.dc: dc1
    cassandraclusters.db.orange.com.rack: rack2
    cluster: k8s.pic
    controller-revision-hash: cassandra-e2e-dc1-rack2-9b4f78944
    dc-rack: dc1-rack2
    operation-end: 20190826T133126
    operation-name: cleanup
    operation-start: 20190826T133124
    operation-status: Done
```

I think that there is a race condition because the behavior is not consistent. It does not happy every time, but I am able to reproduce the problem pretty easily.

The last time I tested and reproduced the bug, I went ahead reset the `operation-status` label back to `ToDo`. This time the rack status was updated as expected.

**Comment by allamand** [comment] 2019-08-26 14:23
Hi John, I think this is relative to this bug : https://github.com/Orange-OpenSource/cassandra-k8s-operator/issues/10

**Comment by Orange-cscetbon** [comment] 2019-09-01 14:13
Duplicate of #10

**Closed** 2019-09-01 14:13 UTC
